### ISSUE TITLE
malformed taxonomy file filename

### ISSUE THREAD

**Issue by thecorz** [epi2me-labs/kraken2-server#1]
Hi,

I'm trying to debug one of the epi2me-labs workflows, wf-metagenomics, which uses this repo to create a k2 server. When I run the pipeline in nextflow it doesn't throw an error, but it gets stuck when the client can't connect to the server. 
So I tried to run the server to see where the problem is, but it's throwing an error:
`kraken2_server: malformed taxonomy file path/to/database/folder/k2_pluspfp_16gb_20220908taxo.k2d`

I tried different databases and they all failed.

I also used kraken2 directly using these databases and it works without a problem. So the problem must be in kraken2-server. I don't do c++ so it's a bit difficult for me to go a bit deeper

**Comment by cjw85** [comment]
The server is mostly a fork of the kraken2 repository so I'm somewhat at a loss as to why the server would claim a taxonomy file is currupt if it works with the original kraken2.

I will download that database and have a look --- I presume its the one from https://benlangmead.github.io/aws-indexes/k2

**Comment by thecorz** [comment]
yes, that's right, that is the one

**Comment by thecorz** [comment]
ok I think I found what the issue was. the script expects a slash at the end of the path to the folder containing the kraken2 db. My statement was missing the slash, that's why the error message shows full location path without the slash between the parent directory and the file name.

**Comment by cjw85** [comment]
Ah yes, this is a bit of a inconvenience that is on my to do list to fix.

**Comment by cjw85** [comment]
This has been fixed in v0.0.10, which will be released shortly.
