### ISSUE TITLE
Cannot execute download_taxonomy.sh, permission denied

### ISSUE THREAD

**Issue by tingning-94** [epi2me-labs/kraken2-server#2]
type "kraken2-build --download-taxonomy --db /data/tingning/kraken2/database"
error: Can't exec "download_taxonomy.sh": Permission denied at /bin/kraken2-build line 290.

May I know whether anyone of you face this issue before?

Thank you.

**Comment by cjw85** [comment]
Hi @tingning-94,

Your question is unrelated to this kraken2-server project, you should instead ask your question over at https://github.com/DerrickWood/kraken2.
