### ISSUE TITLE
Advantages over pre-loading db into RAM?

### ISSUE THREAD

**Issue by ChillarAnand** [epi2me-labs/kraken2-server#6]
kraken2 provides `--memory-mapping` option. We can use `/dev/shm/` (shared memory) to preload db and run classification continuously. I wrote a blog post about the same here https://avilpage.com/2024/07/mastering-kraken2-performance-optimisation.html

Any advantages of using kraken2-server over preload?

**Comment by cjw85** [comment]
This project's primary aim was to create the server component to enable remote clients to perform classifications. It does have the side effect that it can be used in a manner similar to memory mapping files into shm; which is likely preferable if working on a single computer (there are overheads to the server-client setup).

**Comment by ChillarAnand** [comment]
I see. Thanks for the clarification, @cjw85
